[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
  ZinggJM/GxEPD2
  adafruit/Adafruit GFX Library

[env:test]
build_src_filter = -<*> +<test/*>
[env:menu]
build_src_filter = -<*> +<menu/*>
[env:file_system]
build_src_filter = -<*> +<file_system/*>
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
